"""add action_items table

Revision ID: 400768fb0c19
Revises: 315a3ae88619
Create Date: 2026-02-19 19:41:10.548297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400768fb0c19'
down_revision: Union[str, Sequence[str], None] = '315a3ae88619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'idx', name='uq_action_items_job_idx')
    )
    op.create_index(op.f('ix_action_items_job_id'), 'action_items', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_items_job_id'), table_name='action_items')
    op.drop_table('action_items')
    # ### end Alembic commands ###
