"""create artifacts table

Revision ID: 98e9a5cb1d95
Revises: 61e89027267c
Create Date: 2026-02-16 18:35:45.637273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98e9a5cb1d95'
down_revision: Union[str, Sequence[str], None] = '61e89027267c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('storage_uri', sa.String(length=2048), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_content_sha256'), 'artifacts', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_artifacts_type'), 'artifacts', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_type'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_content_sha256'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
