"""add job idempotency unique constraint

Revision ID: cbba12347547
Revises: 0864bdc208d3
Create Date: 2026-02-16 13:17:29.655687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbba12347547'
down_revision: Union[str, Sequence[str], None] = '0864bdc208d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_jobs_user_idempotency_key', 'jobs', ['user_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_user_idempotency_key', 'jobs', type_='unique')
    # ### end Alembic commands ###
