"""create videos table

Revision ID: f7b24305b759
Revises: 74e993e3c791
Create Date: 2026-02-16 12:48:01.920706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b24305b759'
down_revision: Union[str, Sequence[str], None] = '74e993e3c791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_video_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_fingerprint'), 'videos', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_videos_source'), 'videos', ['source'], unique=False)
    op.create_index(op.f('ix_videos_source_video_id'), 'videos', ['source_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_source_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_source'), table_name='videos')
    op.drop_index(op.f('ix_videos_fingerprint'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
